version: '3.8'

services:

  mongodb:
    image : mongo:latest
    container_name: mongodb-nestjs-login
    restart: always 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - nesjs-network

  nestjs-login:
    container_name: nestjs-login
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/opt/workspace/nestjs-login
      - /opt/workspace/nestjs-login/node_modules
    networks:
      - nesjs-network
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  data:
    driver: local

networks:
    nesjs-network:
      driver: bridge