version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb-app-login
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-login-network

  app-login:
    container_name: app-login
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports: 
      - "3000:3000"
    volumes:
      - .:/opt/workspace/gemba-docker-for-nestjs
      - /opt/workspace/gemba-docker-for-nestjs/node_modules
    networks:
      - app-login-network
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  data:
    driver: local

networks:
  app-login-network:
    driver: bridge